baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[content]
name = "test"

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  favicon = "img/face.png"

  [params.twitter]
    creator = "zboknows"
    site = "https://twitter.com/zboknows?lang=en"

[languages]
  [languages.en]
    title = "Zoe Statman-Weil"
    subtitle = "A site about me!"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "ZOE STATMAN-WEIL"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
